version: '3'
services:
  web:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./web:/var/www/html
      - ./conf.d:/etc/nginx/conf.d
    links:
      - php
  php:
    image: php
    volumes:
      - ./web:/var/www/html
    tty: true