version: '2'
services:
  web:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./web:/var/www/html
      - ./conf.d:/etc/nginx/conf.d
    links:
      - php
    networks:
      - mentorship-network
  php:
    image: php:fpm
    volumes:
      - ./web:/var/www/html
    networks:
      - mentorship-network
    expose:
      - 9000
    # tty: true
networks:
  mentorship-network:
    driver: bridge